### ISSUE TITLE
waitvblank() fix

### ISSUE THREAD

**Issue by james7780** [envenomator/Agon#1]
_waitvblank: in mos-interface.asm should use IX register, not IY. Attached file has fixed code for _waitvblank, _getsysvar8bit, and _getsysvar16bit:  (may have some mistakes, my Z80 asm is very rusty)

[mos-interface.zip](https://github.com/envenomator/Agon/files/10849704/mos-interface.zip)

**Comment by envenomator** [comment]
Hi James,
Thanks for bringing this up; sysvars are indeed returned using the IX register. I had changed this for other routines as well about 4 days ago, and also changed this for waitvblank at that time. You can pull the latest changes so see them all.
