### ISSUE TITLE
vdp_spriteSetFrame() bug

### ISSUE THREAD

**Issue by james7780** [envenomator/Agon#2]
In vdp.c :

void vdp_spriteSetFrame(UINT8 id, UINT8 framenumber)
{
	vdp_spriteSelect(id);
	vdp_spriteNextFrameSelected();
	return;
}

Should replace vdp_spriteNextFrameSelected() with vdp_spriteSetFrameSelected(framenumber)

I think the same bug is in vdp.c in hexload and sokoban too.

**Comment by envenomator** [comment]
Fixed in commit 6abba30 - Thanks!
